create sequence hibernate_sequence start with 1 increment by 1
create table country (id bigint not null, country_code varchar(2) not null, full_name varchar(255) not null, primary key (id))
create table listen (id bigint generated by default as identity, listen_date timestamp, song_id bigint, user_id bigint, primary key (id))
create table listener (id bigint not null, birth_date date, gender varchar(1) not null, mail varchar(255) not null, nick_name varchar(255) not null, password varchar(255) not null, user_name varchar(255) not null, country_id bigint, primary key (id))
create table song (id bigint generated by default as identity, album varchar(255) not null, artist varchar(255) not null, title varchar(255) not null, primary key (id))
alter table listener add constraint mail_constraint unique (mail);
alter table listener add constraint username_constraint unique (user_name);
alter table song add constraint song_constraint unique (title, artist, album);
alter table listen add constraint SONG_ID_FK foreign key (song_id) references song;
alter table listen add constraint USER_ID_FK foreign key (user_id) references listener;
alter table listener add constraint COUNTRY_ID_FK foreign key (country_id) references country;

